version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/rails
    networks:
      - custom_pc_builder_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: custom_pc_builder_development
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-h", "localhost", "-U", "postgres"]
      interval: 10s
      retries: 5
    networks:
      - custom_pc_builder_network

networks:
  custom_pc_builder_network:
    driver: bridge